// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CheckboxController from "./checkbox_controller"
application.register("checkbox", CheckboxController)

import ChoicesController from "./choices_controller"
application.register("choices", ChoicesController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import PagyInitializerController from "./pagy_initializer_controller"
application.register("pagy-initializer", PagyInitializerController)

import PullBatchController from "./pull_batch_controller"
application.register("pull-batch", PullBatchController)

import QuickViewController from "./quick_view_controller"
application.register("quick-view", QuickViewController)
