# fly.toml app configuration file generated for iron-tusk-toolbox on 2025-07-13T17:17:57-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'iron-tusk-toolbox'
primary_region = 'ewr'
console_command = '/rails/bin/rails console'

[processes]
  web = "bin/rails s -b 0.0.0.0"
  jobs = "bundle exec good_job start"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['web']

  [[http_service.checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'
    method = 'GET'
    path = '/up'
    protocol = 'http'
    tls_skip_verify = false

    [http_service.checks.headers]
      X-Forwarded-Proto = 'https'

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
